name = "Novis - Recipes"
license = "MIT"
licenselink = "https://github.com/timnovis/recipes/blob/master/themes/recipes/LICENSE.md"
description = "My personal recipe collection"
homepage = "https://recipes.novis.co"
tags = []
features = []
min_version = "0.31.1"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""